# Generated by Django 3.2.7 on 2023-01-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_auto_20230115_1027'),
        ('questions', '0002_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='answers.Answer'),
        ),
    ]
