# Generated by Django 3.2.7 on 2023-01-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
    ]
