# Generated by Django 3.2.7 on 2023-01-12 22:30

import apps.courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('resources', '0001_initial'),
        ('comments', '0001_initial'),
        ('pricing', '0001_initial'),
        ('sections', '0001_initial'),
        ('requisites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.courses.models.course_thumbnail_directory_path)),
                ('sale_video', models.FileField(blank=True, upload_to=apps.courses.models.course_sale_video_path)),
                ('course_type', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='paid', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('sold', models.IntegerField(blank=True, default=0)),
                ('course_length', models.CharField(default=0, max_length=64)),
                ('best_seller', models.BooleanField(default=False)),
                ('total_stars', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='comments.Comment')),
                ('pricing_tiers', models.ManyToManyField(blank=True, to='pricing.Pricing')),
                ('requisite', models.ManyToManyField(blank=True, to='requisites.Requisite')),
                ('resources', models.ManyToManyField(blank=True, to='resources.Resource')),
                ('sections', models.ManyToManyField(blank=True, to='sections.Section')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
            options={
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='PaidCoursesLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(blank=True, to='courses.Course')),
            ],
            options={
                'verbose_name_plural': 'Purchased Courses Library',
            },
        ),
        migrations.CreateModel(
            name='CoursesLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(blank=True, to='courses.Course')),
            ],
            options={
                'verbose_name_plural': 'Bookmarked Courses Library',
            },
        ),
    ]
