# Generated by Django 3.2.7 on 2023-01-09 21:25

import apps.courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.courses.models.course_lessons_path)),
                ('content', models.TextField()),
                ('length', models.DecimalField(decimal_places=2, max_digits=100)),
                ('lesson_number', models.IntegerField(blank=True, default=0, null=True)),
                ('questions', models.ManyToManyField(blank=True, to='courses.Question')),
                ('resources', models.ManyToManyField(blank=True, to='courses.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('lesson_number',),
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='episodes',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.AddField(
            model_name='section',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='courses.Lesson'),
        ),
    ]
