# Generated by Django 3.2.7 on 2023-01-15 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_remove_section_lessons'),
        ('lessons', '0002_remove_lesson_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
    ]
