# Generated by Django 3.2.7 on 2023-01-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20230112_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_accepted_answer',
            new_name='accepted_answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='votes',
            new_name='vote',
        ),
    ]
