# Generated by Django 3.2.7 on 2023-01-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20230112_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='vote',
        ),
    ]
