# Generated by Django 3.2.7 on 2023-01-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_remove_answer_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='negative_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='positive_votes',
        ),
    ]
