# Generated by Django 3.2.7 on 2023-01-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_auto_20230115_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
