# Generated by Django 3.2.7 on 2023-01-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_answers'),
        ('answers', '0006_remove_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='accepted_answer',
            new_name='accepted',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
            preserve_default=False,
        ),
    ]
